name: Publish to prerelease npm
on:
  workflow_dispatch:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make prerelease to npm
        uses: epeli/npm-release@v2
        with:
          type: prerelease
          token: ${{ secrets.NPM_TOKEN }}
